version: '3.8'

services:
  postgres:
    build: ./postgreSQL
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: qwerty123
      DB_NAME: postgres
    entrypoint: ["sh", "-c", "sleep 5 && /app/main"]
    ports:
      - "8080:8080"

volumes:
  postgres_data:
