services:
  postgres:
    build: ./postgreSQL
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty123
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: my_backend
    restart: always
    depends_on:
      - postgres
    environment:
      CORS_ALLOWED_ORIGINS: "*"
      DB_HOST: postgres 
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: qwerty123
      DB_NAME: postgres
    entrypoint: ["sh", "-c", "sleep 3 && /app/main"]
    ports:
      - "8080:8080"

  pinger:
    build: ./pinger
    container_name: my_pinger
    restart: "no"
    depends_on:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"

  frontend:
    build: ./frontend
    container_name: my_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080

volumes:
  postgres_data:
